### ISSUE TITLE
 [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: The signature algorithm is not supported.

### ISSUE THREAD

**Issue by robbiewu007** [VonSdite/Aria2#1]
02/28 00:53:22 [NOTICE] Downloading 1 item(s)

02/28 00:53:22 [ERROR] CUID#7 - Download aborted. URI=https://d.pcs.baidu.com/file/14920816e71cf338c321f214e0fab1e7?fid=3800420369-250528-19503251595643&time=1488214141&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-CRST7M1gtzS6418kdTCEn1K7CgE%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=1345973350375283597&dp-callid=0&r=711056556
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://d.pcs.baidu.com/file/14920816e71cf338c321f214e0fab1e7?fid=3800420369-250528-19503251595643&time=1488214141&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-CRST7M1gtzS6418kdTCEn1K7CgE%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=1345973350375283597&dp-callid=0&r=711056556
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: The signature algorithm is not supported.

02/28 00:53:22 [NOTICE] Download GID#0a9792fd594ae51d not complete: /home/buildslave/happy_times/ImageNet_Dataset/ILSVRC2012.z30

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0a9792|ERR |       0B/s|/home/buildslave/happy_times/ImageNet_Dataset/ILSVRC2012.z30

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by robbiewu007** [comment]
复现步骤：
1. 在Window 10机器上面，用Chrome浏览器，通过ARIA2插件导出；
2. 在另外一台Ubuntu Linux，运行aria2c下载；
3. 提示无法下载。

**Comment by VonSdite** [comment]
@robbiewu007 
抱歉，， 因为最近都有别的事在忙，所以没上github。
恩，这个问题我也不清楚， 但是github上已有小伙伴解决了，
可能是 gnutls版本太老。
详情见：https://github.com/aria2/aria2/issues/848

**Comment by robbiewu007** [comment]
自个编译aria2的有问题，用ubuntu维护旧版本deb包没有问题。

**Comment by chucklvip** [comment]
add this extra setting when aria2c start (Perhaps it should be written to the configuration file)

`check-certificate=false`

**Comment by lhuang001** [comment]
I meet this problem today. aria2 version is 1.19 installed by apt-get on ubuntu 16.04, unfortunately check-certificate=false doesn't work on my mechine.  finally i compile aria 1.34  with --without-gnutls --with-openssl. now everything is ok.:)
